# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [5]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [13]:
A = np.arange(1, 16).reshape(3,5)

In [14]:
A


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
A.shape # shape of the array

(3, 5)

In [ ]:
A.size # antal element

15

In [ ]:
A.dtype # data type of array elements

dtype('int64')

In [ ]:
A.ndim # antal dimensioner


2

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [51]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [53]:
A = B - C
A


array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [54]:
A = B + C
A



array([[ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [55]:
A = B @ C
A

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [ ]:
D = np.arange(1, 10).reshape(3, 3) # 3x3 matrix with values from 1 to 9
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
E = np.exp(D) # e upphöjt till varje element i D
print(E)
E

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [ ]:
E = D.min() #  minimum value in D
print(E)
E

1


np.int64(1)

In [ ]:
E = D.min(axis=0) # minimum value in each column
print(E)
E

[1 2 3]


array([1, 2, 3])

In [ ]:
E = D.min(axis=1) # minimum value in each row
print(E)
E

[1 4 7]


array([1, 4, 7])

In [59]:
# F = D.flat[np.argmin(D, axis=1)]
F = np.argmin(D) # position i 1D-array
print(F)
F

0


np.int64(0)

In [60]:
# F = D.flat[np.argmin(D, axis=1)]
F = np.argmin(D, axis=1)
print(F)
F

[0 0 0]


array([0, 0, 0])

In [61]:
S = D.sum() # sum of all elements
print(D) # print the original array D for reference
print(S)
S

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45


np.int64(45)

In [62]:
M1 = D.mean(axis=0) # column-wise medelvärde
print(M1)
M1

[4. 5. 6.]


array([4., 5., 6.])

In [63]:
M = np.median(D, axis=0) # column-wise median
print(M)
M

[4. 5. 6.]


array([4., 5., 6.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [68]:
A = np.arange(1, 16).reshape(3,5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [69]:
A[1,2]

np.int64(8)

**Answer:**

In [70]:
# Färre specifierade index ger större mängd data. A ger hela matrisen, A[1] ger andra raden och A[1,2] 
# ger elementet i andra raden och tredje kolumnen.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [71]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [72]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [73]:
 for i in A.flat: # Loopar igenom alla element i matrisen A som en 1D-array
    print(i)

print('-------X-------')

B = A.flatten() # Snyggare och enklare än ovan
print(B)
print(B[2]+B[8]) # <test> Summera 2:a och 8:e elementet i 1D-arrayen (indexering från 0)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
-------X-------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
12


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [74]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [75]:
# Vi konverterar en 1D-array till en 3D-array med 2 block, 3 rader och automatiskt beräknat antal kolumner (-1). 
# 1D-arrayen måste ha rätt antal element för att detta ska fungera (annars blir det fel).

# (Man kan också använda .reshape(2, 3, 5) direkt utan -1 i detta fall. Det fungerar också med 
# b = np.reshape(a, (2, 3, -1)) )

### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [76]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [77]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [78]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [ ]:
# numpy is already imported in an earlier cell, do not re-import here

def add_mult_matrices(m1, m2, oper: str):
    """
    Add or multiply two numpy arrays.
    oper: 'add' or '+'        -> elementwise addition (requires same shape)
          'multiply' or '*'   -> matrix multiplication (requires m1.shape[1] == m2.shape[0])
    """
    if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray):
        raise TypeError("m1 & m2 måste vara av typen numpy.ndarray")

    if oper in ('plus', '+'):
        if m1.shape != m2.shape:
            raise ValueError("För addition, matrisen måste ha samma form")
        return m1 + m2
    elif oper in ('ganger', '*'):
        if m1.ndim != 2 or m2.ndim != 2:
            raise ValueError("Matrix multiplikation måste vara 2D-arrayer")
        if m1.shape[1] != m2.shape[0]:
            raise ValueError("För Matrismultiplikation, antal kolumner i första matrisen måste vara lika många som rader i andra matrisen")
        return m1 @ m2
    else:
        raise ValueError("Felaktig operator! oper måste vara 'plus'/'+' eller 'ganger'/'*'")

# --- Main start ---
A = np.asarray(((1, 2), (3, 4))) # A = (1,2,3,4,5) B = (6,7,8,9,10) skall det vara?
B = np.asarray(((5, 6), (7, 8)))
# C = np.asarray(((1, 2), (3, 4)))

# print("isinstance(C, np.ndarray):", isinstance(C, np.ndarray))

print("Sum (elementwise addition):\n", add_mult_matrices(A, B, '+'), "\n")
print("Matrix multiplication (A @ B):\n", add_mult_matrices(A, B, '*'), "\n")

print("A:\n", A)
print("type(A):", type(A))

Sum (elementwise addition):
 [[ 6  8]
 [10 12]] 

Matrix multiplication (A @ B):
 [[19 22]
 [43 50]] 

A:
 [[1 2]
 [3 4]]
type(A): <class 'numpy.ndarray'>


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)