In [11]:
import numpy as np
# a = np.arange(9).reshape(3,3) + 10
a = np.array([[10, 20], [5, 25], [15, 8]])
print(a)
print()
print(np.argmin(a))
print(np.argmin(a, axis=0))
print(np.argmin(a, axis=1))
print()
print(a.shape[0])
print(a.mean(axis=0))
print(np.median(a, axis=0))

[[10 20]
 [ 5 25]
 [15  8]]

2
[1 2]
[0 0 1]

3
[10.         17.66666667]
[10. 20.]


# Lägsta värdet i matrisen är på pos 2, dvs '5' (0, 1, 2, etc, gäller även i matriser, axis 1 x, axis 0 y)

# [1 2] - Kolumnvis, 2 kolumner (10,5,15) och (20,25,8), lägsta värdet i 1:a kol '5' rad 1, 2:a kol '8' rad 2

# [0 0 1] - Radvis, 3 rader (10,20), (5,25) och (15,8), lägsta värdet i 1:a rad '10' kol 0, 2:a rad '5' kol 0 och 3:e rad '8' kol 1
