In [12]:
import numpy as np
# a = np.arange(9).reshape(3,3) + 10
a = np.array([[10, 20], [5, 25], [15, 8]])
print(a)
print()
print(np.argmin(a))
print(np.argmin(a, axis=0))
print(np.argmin(a, axis=1))
print()
print(a.shape[0])
print(a.mean(axis=0))
print(np.median(a, axis=0))

##################
# important part!
##################

import numpy as np

####################
# toy array for demo
####################

arr = np.asarray(range(1,100,2))
A = np.asarray(((1,2),(3,4)))

########################
# The instance check
######################## 

C = isinstance(A,np.ndarray)
C

[[10 20]
 [ 5 25]
 [15  8]]

2
[1 2]
[0 0 1]

3
[10.         17.66666667]
[10. 20.]


True

# Lägsta värdet i matrisen är på pos 2, dvs '5' (0, 1, 2, etc, gäller även i matriser, axis 1 x, axis 0 y)

# [1 2] - Kolumnvis, 2 kolumner (10,5,15) och (20,25,8), lägsta värdet i 1:a kol '5' rad 1, 2:a kol '8' rad 2

# [0 0 1] - Radvis, 3 rader (10,20), (5,25) och (15,8), lägsta värdet i 1:a rad '10' kol 0, 2:a rad '5' kol 0 och 3:e rad '8' kol 1


In [14]:
# numpy is already imported in an earlier cell, do not re-import here

def add_mult_matrices(m1, m2, oper: str):
    """
    Add or multiply two numpy arrays.
    oper: 'add' or '+'        -> elementwise addition (requires same shape)
          'multiply' or '*'   -> matrix multiplication (requires m1.shape[1] == m2.shape[0])
    """
    if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray):
        raise TypeError("m1 and m2 must be numpy.ndarray")

    if oper in ('add', '+'):
        if m1.shape != m2.shape:
            raise ValueError("For addition, matrices must have the same shape")
        return m1 + m2
    elif oper in ('multiply', '*'):
        if m1.ndim != 2 or m2.ndim != 2:
            raise ValueError("Matrix multiplication requires 2D arrays")
        if m1.shape[1] != m2.shape[0]:
            raise ValueError("For matrix multiplication, number of columns in the first matrix must equal number of rows in the second")
        return m1 @ m2
    else:
        raise ValueError("oper must be 'add'/'+' or 'multiply'/'*'")

A = np.asarray(((1, 2), (3, 4)))
B = np.asarray(((5, 6), (7, 8)))


# print("isinstance(C, np.ndarray):", isinstance(C, np.ndarray))

print("Sum (elementwise addition):\n", add_mult_matrices(A, B, '+'), "\n")
print("Matrix multiplication (A @ B):\n", add_mult_matrices(A, B, '*'), "\n")

print("A:\n", A)
print("type(A):", type(A))

Sum (elementwise addition):
 [[ 6  8]
 [10 12]] 

Matrix multiplication (A @ B):
 [[19 22]
 [43 50]] 

A:
 [[1 2]
 [3 4]]
type(A): <class 'numpy.ndarray'>
