In [12]:
import numpy as np
# a = np.arange(9).reshape(3,3) + 10
a = np.array([[10, 20], [5, 25], [15, 8]])
print(a)
print()
print(np.argmin(a))
print(np.argmin(a, axis=0))
print(np.argmin(a, axis=1))
print()
print(a.shape[0])
print(a.mean(axis=0))
print(np.median(a, axis=0))

##################
# important part!
##################

import numpy as np

####################
# toy array for demo
####################

arr = np.asarray(range(1,100,2))
A = np.asarray(((1,2),(3,4)))

########################
# The instance check
######################## 

C = isinstance(A,np.ndarray)
C

[[10 20]
 [ 5 25]
 [15  8]]

2
[1 2]
[0 0 1]

3
[10.         17.66666667]
[10. 20.]


True

# Lägsta värdet i matrisen är på pos 2, dvs '5' (0, 1, 2, etc, gäller även i matriser, axis 1 x, axis 0 y)

# [1 2] - Kolumnvis, 2 kolumner (10,5,15) och (20,25,8), lägsta värdet i 1:a kol '5' rad 1, 2:a kol '8' rad 2

# [0 0 1] - Radvis, 3 rader (10,20), (5,25) och (15,8), lägsta värdet i 1:a rad '10' kol 0, 2:a rad '5' kol 0 och 3:e rad '8' kol 1


In [ ]:
# numpy is already imported in an earlier cell, do not re-import here

import numpy as np

def add_mult_matrices(m1, m2, oper: str):
    """
    Add or multiply two numpy arrays.
    oper: 'add' or '+'        -> elementwise addition (requires same shape)
          'multiply' or '*'   -> matrix multiplication (requires m1.shape[1] == m2.shape[0])
    """
    if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray):
        raise TypeError("m1 and m2 must be numpy.ndarray")

    if oper in ('add', '+'):
        if m1.shape != m2.shape:
            raise ValueError("For addition, matrices must have the same shape")
        return m1 + m2
    elif oper in ('multiply', '*'):
        if m1.ndim != 2 or m2.ndim != 2:
            raise ValueError("Matrix multiplication requires 2D arrays")
        if m1.shape[1] != m2.shape[0]:
            raise ValueError("For matrix multiplication, number of columns in the first matrix must equal number of rows in the second")
        return m1 @ m2
    else:
        raise ValueError("oper must be 'add'/'+' or 'multiply'/'*'")

# --- Main start ---
i : int
x1 = np.zeros((8,), dtype=int)
y1 = np.zeros((8,), dtype=int)

print(x1, y1)
#A = np.asarray(((1, 2), (3, 4)))
#B = np.asarray(((5, 6), (7, 8)))
#np.append(A, B, axis=0)
A = list()
B = list()
cont = True
i = 0

while cont:
    x1[i] = input("Enter element x{} of matrix 1: ".format(i+1))
    y1[i] = input("Enter element y{} of matrix 1: ".format(i+1))
#    A = np.asarray(((x1[0], X1[1]), (x1[2], x1[3])))
#    B = np.asarray(((y1[0], y1[1]), (y1[2], y1[3])))
    if i < 5:
        A.append([x1[i], y1[i]])
        print("A:", A[i])
    else:
        B.append([x1[i], y1[i]])
        print("B:", B)
    i += 1
    if i > 8:
        cont = False 

print("Sum (elementwise addition):\n", add_mult_matrices(A, B, '+'), "\n")
print("Matrix multiplication (A @ B):\n", add_mult_matrices(A, B, '*'), "\n")

#print("A:\n", A)
#print("type(A):", type(A))

[0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0]
A: [np.int64(1), np.int64(2)]
A: [np.int64(3), np.int64(4)]
A: [np.int64(5), np.int64(6)]
A: [np.int64(7), np.int64(8)]
A: [np.int64(9), np.int64(0)]
B: [[np.int64(12), np.int64(11)]]
B: [[np.int64(12), np.int64(11)], [np.int64(22), np.int64(33)]]
B: [[np.int64(12), np.int64(11)], [np.int64(22), np.int64(33)], [np.int64(44), np.int64(55)]]


IndexError: index 8 is out of bounds for axis 0 with size 8

In [69]:
# numpy is already imported in an earlier cell, do not re-import here

import numpy as np

def add_mult_matrices(m1, m2, oper: str):
    """
    Add or multiply two numpy arrays.
    oper: 'add' or '+'        -> elementwise addition (requires same shape)
          'multiply' or '*'   -> matrix multiplication (requires m1.shape[1] == m2.shape[0])
    """
    if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray):
        raise TypeError("m1 and m2 must be numpy.ndarray")

    if oper in ('add', '+'):
        if m1.shape != m2.shape:
            raise ValueError(f"For addition, matrices must have the same shape {m1.shape} <> {m2.shape}")
        return m1 + m2
    elif oper in ('multiply', '*'):
        if m1.ndim != 2 or m2.ndim != 2:
            raise ValueError("Matrix multiplication requires 2D arrays")
        if m1.shape[1] != m2.shape[0]:
            raise ValueError(f"For matrix multiplication, number of columns in the first matrix {m1.shape[1]} must equal number of rows in the second")
        return m1 @ m2
    else:
        raise ValueError("oper must be 'add'/'+' or 'multiply'/'*'")

# --- Main start ---
i : int

# initialize control variables
cont = False
i = 0

# initialize A and B as numpy arrays (correct ndarray construction)
A = np.array([[10, 20, 1], [5, 25, 2], [15, 8, 3]])
B = np.array([[10, 20, 5], [25, 15, 8], [6, 1, 10]])

print(A, A.shape)
print(B, B.shape)

#A = np.ndarray([[1,2],[3,4]])
#B = np.ndarray([[5,6],[7,8]])

while cont:
    x1[i] = input("Enter element x{} of matrix 1: ".format(i+1))
    y1[i] = input("Enter element y{} of matrix 1: ".format(i+1))
#    A = np.asarray(((x1[0], X1[1]), (x1[2], x1[3])))
#    B = np.asarray(((y1[0], y1[1]), (y1[2], y1[3])))
    if i < 5:
        A.append([x1[i], y1[i]])
        print("A:", A[i])
    else:
        B.append([x1[i], y1[i]])
        print("B:", B)
    i += 1
    if i > 8:
        cont = False 

print("Sum (elementwise addition):\n", add_mult_matrices(A, B, '+'), "\n")
print("Matrix multiplication (A @ B):\n", add_mult_matrices(A, B, '*'), "\n")

#print("A:\n", A)
#print("type(A):", type(A))

[[10 20  1]
 [ 5 25  2]
 [15  8  3]] (3, 3)
[[10 20  5]
 [25 15  8]
 [ 6  1 10]] (3, 3)
Sum (elementwise addition):
 [[20 40  6]
 [30 40 10]
 [21  9 13]] 

Matrix multiplication (A @ B):
 [[606 501 220]
 [687 477 245]
 [368 423 169]] 

